"""empty message

Revision ID: bc00efe29153
Revises: 819cbf6e030b
Create Date: 2023-10-21 09:47:32.219365

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bc00efe29153"
down_revision = "819cbf6e030b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bus_stop",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("location", sa.String(length=512), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bus",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=10), nullable=False),
        sa.Column("destination", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["destination"],
            ["bus_stop.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bus_route",
        sa.Column("bus_id", sa.Integer(), nullable=False),
        sa.Column("bus_stop_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bus_id"],
            ["bus.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bus_stop_id"],
            ["bus_stop.id"],
        ),
        sa.PrimaryKeyConstraint("bus_id", "bus_stop_id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("role", sa.String(length=20), server_default="USER", nullable=False),
        sa.Column("totp_secret", sa.String(length=100), nullable=True),
        sa.Column(
            "totp_created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("boarding_bus_id", sa.Integer(), nullable=True),
        sa.Column("destination_stop_id", sa.Integer(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["boarding_bus_id"],
            ["bus.id"],
        ),
        sa.ForeignKeyConstraint(
            ["destination_stop_id"],
            ["bus_stop.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "boarding_record",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("destination_stop_id", sa.Integer(), nullable=False),
        sa.Column("boarding_bus_id", sa.Integer(), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["boarding_bus_id"],
            ["bus.id"],
        ),
        sa.ForeignKeyConstraint(
            ["destination_stop_id"],
            ["bus_stop.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bus_admin",
        sa.Column("bus_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["bus_id"],
            ["bus.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("bus_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bus_admin")
    op.drop_table("boarding_record")
    op.drop_table("user")
    op.drop_table("bus_route")
    op.drop_table("bus")
    op.drop_table("bus_stop")
    # ### end Alembic commands ###
