"""empty message

Revision ID: 7d6141d9c1c7
Revises: bc00efe29153
Create Date: 2023-11-15 00:54:42.654994

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7d6141d9c1c7"
down_revision = "bc00efe29153"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "boarding_record", sa.Column("verified", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("boarding_record", "verified")
    # ### end Alembic commands ###
