version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: ghcr.io/gbswhs/bus_boarding_api:latest
    restart: always
    ports:
      - 8000:8000
    networks:
      - bus_boarding
    env_file:
    - .env
    environment:
      BUS_BOARDING_API_HOST: 0.0.0.0
      BUS_BOARDING_API_DB_HOST: bus_boarding_api-db
      BUS_BOARDING_API_DB_PORT: 3306
    depends_on:
      db:
        condition: service_started

  db:
    image: mariadb:10.11
    hostname: bus_boarding_api-db
    restart: always
    expose:
      - 3306
    networks:
      - bus_boarding
    command: --max_allowed_packet=32505856
    env_file:
      - .env
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
    - bus_boarding_api-db-data:/var/lib/mysql

  migrator:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: ghcr.io/gbswhs/bus_boarding_api:latest
    restart: "no"
    entrypoint: python3 -m alembic upgrade head
    networks:
      - bus_boarding
    env_file:
      - .env
    depends_on:
      db:
        condition: service_started

  adminer:
      image: adminer
      restart: always
      ports:
          - 8080:8080
      networks:
          - bus_boarding
      depends_on:
        db:
          condition: service_started


networks:
  bus_boarding:

volumes:
  bus_boarding_api-db-data:
    name: bus_boarding_api-db-data
