version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: bus_boarding_api:${BUS_BOARDING_API_VERSION:-latest}
    restart: always
    ports:
      - 8000:8000
    networks:
      - bus_boarding
    env_file:
    - .env
    environment:
      BUS_BOARDING_API_HOST: 0.0.0.0
      BUS_BOARDING_API_DB_HOST: bus_boarding_api-db
      BUS_BOARDING_API_DB_PORT: 3306
      BUS_BOARDING_API_DB_USER: bus_boarding_api
      BUS_BOARDING_API_DB_PASS: bus_boarding_api
      BUS_BOARDING_API_DB_BASE: bus_boarding_api
      BUS_BOARDING_API_REDIS_HOST: bus_boarding_api-redis

  db:
    image: mariadb:latest
    hostname: bus_boarding_api-db
    restart: always
    expose:
      - 3306
    networks:
      - bus_boarding
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_USER: "bus_boarding_api"
      MARIADB_PASSWORD: "bus_boarding_api"
      MARIADB_DATABASE: "bus_boarding_api"
    volumes:
    - bus_boarding_api-db-data:/var/lib/mysql

  migrator:
    image: bus_boarding_api:${BUS_BOARDING_API_VERSION:-latest}
    command: alembic upgrade head
    networks:
      - bus_boarding
    environment:
      BUS_BOARDING_API_DB_HOST: bus_boarding_api-db
      BUS_BOARDING_API_DB_PORT: 3306
      BUS_BOARDING_API_DB_USER: bus_boarding_api
      BUS_BOARDING_API_DB_PASS: bus_boarding_api
      BUS_BOARDING_API_DB_BASE: bus_boarding_api
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s

  adminer:
      image: adminer
      restart: always
      ports:
          - 8080:8080
      networks:
          - bus_boarding
      depends_on:
          - db


networks:
  bus_boarding:

volumes:
  bus_boarding_api-db-data:
    name: bus_boarding_api-db-data
