version: '3.9'

services:
  api:
    image: ghcr.io/gbswhs/bus_boarding_api:latest
    restart: always
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      BUS_BOARDING_API_HOST: 0.0.0.0
      BUS_BOARDING_API_DB_HOST: bus_boarding_api-db
      BUS_BOARDING_API_DB_PORT: 3306
      BUS_BOARDING_API_DB_USER: bus_boarding_api
      BUS_BOARDING_API_DB_PASS: bus_boarding_api
      BUS_BOARDING_API_DB_BASE: bus_boarding_api
      BUS_BOARDING_API_REDIS_HOST: bus_boarding_api-redis

  db:
    image: bitnami/mysql:latest
    hostname: bus_boarding_api-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_USER: "bus_boarding_api"
      MYSQL_ROOT_PASSWORD: "bus_boarding_api"
      MYSQL_DATABASE: "bus_boarding_api"
      MYSQL_AUTHENTICATION_PLUGIN: "caching_sha2_password"
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 10s
      timeout: 5s
      retries: 40
    volumes:
    - bus_boarding_api-db-data:/bitnami/mysql/data

  migrator:
    image: bus_boarding_api:${BUS_BOARDING_API_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      BUS_BOARDING_API_DB_HOST: bus_boarding_api-db
      BUS_BOARDING_API_DB_PORT: 3306
      BUS_BOARDING_API_DB_USER: bus_boarding_api
      BUS_BOARDING_API_DB_PASS: bus_boarding_api
      BUS_BOARDING_API_DB_BASE: bus_boarding_api
    depends_on:
      db:
        condition: service_healthy


volumes:
  bus_boarding_api-db-data:
    name: bus_boarding_api-db-data
