version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.dev
    image: bus_boarding_api:${BUS_BOARDING_API_VERSION:-latest}
    ports:
      # Exposes application port.
    - "8000:8000"
    volumes:
      # Adds current directory as volume.
    - .:/app/src/
    environment:
      # Enables autoreload.
      BUS_BOARDING_API_RELOAD: "True"

  migrator:
    image: bus_boarding_api:${BUS_BOARDING_API_VERSION:-latest}
